apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrcode-backend-deployment
  namespace: qrcode
  labels:
    app: qrcode-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qrcode-backend
  template:
    metadata:
      labels:
        app: qrcode-backend
    spec:
      containers:
      - name: qrcode-backend
        image: matthew10125/qrcode-backend
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  namespace: qrcode
  name: qrcode-backend-svc
spec:
  selector:
    app: qrcode-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

