apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dgc
  name: asynq-data
  labels:
    app: redis
    service: asynq
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/nfs/redis/test/asynq/data
    server: peter.local
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dgc
  name: asynq-data
  labels:
    app: redis
    service: asynq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dgc
  name: asynq-config
  labels:
    app: redis
    service: asynq
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/nfs/redis/test/asynq/config
    server: peter.local
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dgc
  name: asynq-config
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs
