apiVersion: v1
kind: Pod
metadata:
  name: debug
  labels:
    app: debug
spec:
  containers:
  - image: matthew10125/debug
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: debug
  restartPolicy: Always
