apiVersion: v1
kind: PersistentVolume
metadata:
  name: qrcode-pv
  labels:
    app: qrcode-backend
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: <path>
    server: <server_ip>
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qrcode-pvc
  namespace: qrcode
  labels:
    app: qrcode-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
