apiVersion: v1
kind: PersistentVolume
metadata:
  name: qrcode-backend-pv
  labels:
    app: qrcode-backend
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/nfs/qrcode/codes
    server: 10.0.0.249
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qrcode-backend-pvc
  labels:
    app: qrcode-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
