apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: dcr
spec:
  type: ClusterIP
  selector:
    app: docker-registry
    release: docker-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
