apiVersion: v1
kind: Service
metadata:
  name: dgc-backend-svc
  namespace: dgc
  labels:
    app: dgc-backend
spec:
  selector:
    app: dgc-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
  type: ClusterIP
