apiVersion: v1
kind: PersistentVolume
metadata:
  name: dss-storage-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/nfs/dss
    server: 10.0.0.249
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dss-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
