apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
  labels:
    app: mysql
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/nfs/mysql/ghost/data
    server: 10.0.0.249
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-config-pv
  labels:
    app: mysql
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/nfs/mysql/ghost/configs
    server: 10.0.0.249
    readOnly: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-config-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs

