apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
  labels:
    app: ghost
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: <nfs_path>
    server: <server_ip>
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
  namespace: ghost
  labels:
    app: ghost
spec:
  storageClassName: "nfs"
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
