apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: "${NAMESPACE}"
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: NodePort
