apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dgc
  name: postgres-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /var/nfs/volumes/postgres/data
    server: 10.0.0.249
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dgc
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs

